algoritmo "Exemplo 2"
// Função :
// Autor : Felipe Goulart
var
nomePessoa: vetor [1..5] de caractere
contadora: inteiro
inicio
para contadora de 1 ate 5 passo 1 faca
   ESCREVAL("Digite o nome da ", contadora,"ª pessoa:")
   LEIA (nomePessoa[contadora])
fimpara
ESCREVAL
ESCREVAL ("1ª", nomePessoa[1])
ESCREVAL ("2ª", nomePessoa[2])
ESCREVAL ("3ª", nomePessoa[3])
ESCREVAL ("4ª", nomePessoa[4])
ESCREVAL ("5ª", nomePessoa[5])
fimalgoritmo
