algoritmo "Calculadora Automática"
// Função : Valor de Venda do Produto
// Autor : Felipe Goulart
var
valor_compra, porcentagem, valor_venda: real
inicio
ESCREVAL ("Seja bem-vindo, comerciante!")
ESCREVAL
ESCREVAL ("Insira o valor de compra do produto: ")
LEIA (valor_compra)
valor_venda <- 0.35 * (valor_compra) + (valor_compra)
ESCREVAL
ESCREVAL ("O valor de lucro do produto será de: R$", valor_venda:2:2)
fimalgoritmo
