algoritmo "Olha o Aviãozinho"
// Função : Aparecer 10x a frase "a careca do silvio santos brilha"
// Autor : Felipe Goulart
//Faça um algoritmo que mostre na tela 10 vezes a frase
//filosófica: “A careca do Silvio brilha, brilha a careca do Silvio”!
var
contadora: inteiro
inicio
para contadora de 1 ate 10 passo 1 faca
ESCREVAL ("A careca do Silvio brilha, brilha a careca do Silvio!")
fimpara
fimalgoritmo
